env:
	browser: true
	es6: true
	node: true
extends:
	- 'eslint:recommended'
# https://github.com/yannickcr/eslint-plugin-react#configuration
#	- 'plugin:react/recommended'
parser: 'babel-eslint'
parserOptions:
	ecmaVersion: 2018
	ecmaFeatures:
		jsx: true
	sourceType: module
settings:
	react:
		version: 'detect'
plugins:
	- react
	- react-hooks
rules:
	accessor-pairs: error
	array-bracket-newline:
		- error
		- multiline: true
	array-bracket-spacing: error
	array-callback-return: error
	array-element-newline:
		- error
		- consistent
	arrow-body-style: 'off'
	arrow-parens: error
	arrow-spacing:
		- error
		- after: true
			before: true
	block-scoped-var: error
	block-spacing: error
	brace-style:
		- error
		- 1tbs
	callback-return: error
	camelcase:
		- error
		- properties: never
	capitalized-comments: 'off'
	class-methods-use-this: 'off'
	comma-dangle: 'off'
	comma-spacing:
		- error
		- after: true
			before: false
	comma-style: error
	complexity: error
	computed-property-spacing: error
	consistent-this: error
	curly: off
	default-case: error
	dot-location:
		- error
		- property
	dot-notation: error
	eol-last: error
	eqeqeq: error
	for-direction: error
	func-call-spacing: error
	func-name-matching: error
	func-names: error
	function-paren-newline: error
	generator-star-spacing: error
	getter-return: error
	global-require: error
	guard-for-in: error
	handle-callback-err: error
	id-blacklist: error
	id-length: warn
	id-match: error
	implicit-arrow-linebreak:
		- error
		- beside
	indent:
		- 2
		- tab
		- SwitchCase: 1
	indent-legacy: 'off'
	init-declarations: 'off'
	jsx-quotes: error
	key-spacing: error
	keyword-spacing:
		- error
		- after: true
			before: true
	line-comment-position: 'off'
	linebreak-style:
		- error
		- unix
	lines-around-comment: error
	lines-around-directive: error
	lines-between-class-members:
		- error
		- always
	max-depth: error
	max-len: 'off'
	max-lines: warn
	max-nested-callbacks: error
	max-params: 'off'
	max-statements:
		- warn
		- max: 12
		- ignoreTopLevelFunctions: true
	max-statements-per-line: error
	multiline-comment-style: 'off'
	multiline-ternary: 'off'
	new-cap: 'off'
	new-parens: error
	newline-after-var:
		- error
		- always
	newline-before-return: error
	newline-per-chained-call:
		- error
		- ignoreChainWithDepth: 4
	no-alert: warn
	no-array-constructor: error
	no-await-in-loop: error
	no-bitwise: error
	no-buffer-constructor: error
	no-caller: error
	no-catch-shadow: error
	no-console: warn
	no-continue: error
	no-div-regex: error
	no-duplicate-imports: error
	no-else-return: error
	no-empty-function: error
	no-eq-null: error
	no-eval: error
	no-extend-native: error
	no-extra-bind: error
	no-extra-label: error
	no-extra-parens:
		- error
		- all
		- nestedBinaryExpressions: false
			ignoreJSX: 'all'
	no-floating-decimal: error
	no-implicit-coercion: error
	no-implicit-globals: error
	no-implied-eval: error
	no-inline-comments: 'off'
	no-invalid-this: error
	no-iterator: error
	no-label-var: error
	no-labels: error
	no-lone-blocks: error
	no-lonely-if: error
	no-loop-func: error
	no-magic-numbers:
		- warn
		- ignore:
			- -1
			- 0
			- 1
			- 100
	no-mixed-operators: warn
	no-multi-assign: error
	no-multi-spaces: error
	no-multi-str: error
	no-multiple-empty-lines: error
	no-native-reassign: error
	no-negated-condition: 'off'
	no-negated-in-lhs: error
	no-nested-ternary: warn
	no-new: error
	no-new-func: error
	no-new-object: error
	no-new-require: error
	no-new-wrappers: error
	no-octal-escape: error
	no-param-reassign: error
	no-path-concat: error
	no-plusplus:
		- error
		- allowForLoopAfterthoughts: true
	no-process-exit: error
	no-proto: error
	no-prototype-builtins: error
	no-restricted-globals: error
	no-restricted-imports: error
	no-restricted-modules: error
	no-restricted-properties: error
	no-restricted-syntax: error
	no-return-assign: error
	no-return-await: error
	no-script-url: error
	no-self-compare: error
	no-sequences: error
	no-shadow: error
	no-shadow-restricted-names: error
	no-spaced-func: error
	no-sync: error
	no-tabs: 'off'
	no-template-curly-in-string: error
	no-throw-literal: error
	no-trailing-spaces: error
	no-undef-init: error
	no-undefined: error
	no-underscore-dangle: 'off'
	no-unmodified-loop-condition: error
	no-unneeded-ternary: error
	no-unused-expressions: error
	no-use-before-define: 'off'
	no-useless-call: error
	no-useless-computed-key: error
	no-useless-concat: error
	no-useless-constructor: error
	no-useless-rename: error
	no-useless-return: error
	no-unused-vars: 'off'
	no-var: error
	no-void: error
	no-warning-comments: 'off'
	no-whitespace-before-property: error
	no-with: error
	nonblock-statement-body-position: error
	object-curly-newline:
		- error
		- consistent: true
	object-curly-spacing:
		- off
	object-shorthand: error
	one-var:
		- error
		- var: always
			let: consecutive
			const: consecutive
	one-var-declaration-per-line: error
	operator-assignment: error
	operator-linebreak: 'off'
	padded-blocks: 'off'
	padding-line-between-statements: error
	prefer-arrow-callback: error
	prefer-const: error
	prefer-numeric-literals: error
	prefer-promise-reject-errors: error
	prefer-rest-params: error
	prefer-spread: error
	prefer-template: 'off'
	quote-props: 'off'
	quotes:
		- error
		- single
	radix: 'off'
	react/jsx-boolean-value: 'off'
	react/jsx-curly-spacing: 'off'
	react/jsx-max-props-per-line:
		- error
		- maximum: 4
	react/jsx-no-duplicate-props: error
	react/jsx-no-undef: error
	react/jsx-sort-props: 'off'
	react/jsx-uses-react: error
	react/jsx-uses-vars: error
	react/jsx-wrap-multilines: error
	react/no-danger: error
	react/no-did-mount-set-state: error
	react/no-did-update-set-state: error
	react/no-multi-comp:
		- error
		- ignoreStateless: true
	react/no-unknown-property:
		- error
		- ignore:
			- 'datetime' # This is a valid HTML attribute that eslint-plugin-react isn't aware of.
	react/prop-types: error
	react/react-in-jsx-scope: error
	react/self-closing-comp: error
	react/sort-comp:
		- error
		- order:
			- /[A-Z_]+$/
			- /constructor/
			- static-methods
			- lifecycle
			- everything-else
			- render
	react/sort-prop-types: 'off'
	react-hooks/rules-of-hooks: error
	react-hooks/exhaustive-deps: warn
	require-await: error
	require-jsdoc: 'off' # TODO: Turn on
	rest-spread-spacing:
		- error
		- never
	semi: error
	semi-spacing: error
	semi-style:
		- error
		- last
	sort-imports: 'off'
	sort-keys: 'off'
	sort-vars: 'off'
	space-before-blocks: error
	space-before-function-paren: off
	space-in-parens:
		- error
		- never
	space-infix-ops: error
	space-unary-ops: error
	spaced-comment:
		- error
		- always
	strict: error
	switch-colon-spacing: error
	symbol-description: error
	template-curly-spacing: error
	template-tag-spacing: error
	unicode-bom:
		- error
		- never
	valid-jsdoc: error
	vars-on-top: error
	wrap-iife: error
	wrap-regex: error
	yield-star-spacing: error
	yoda: error
